---
title: "UNC_Buoys"
output: html_document
date: "2024-03-04"
---

#Set up environment
```{r}
rm(list=ls()) #clear environment

library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(openair)
library(data.table)
library(RColorBrewer)
library(tidyverse)

#Set working directory
wd <- "C:/Users/OCRONING/OneDrive - Environmental Protection Agency (EPA)/Profile/Documents/Chlorophyll_Temporal_Mismatch/Raw_Data/UNC_Buoys/"

#Output directories
Figure_filepath <- "C:/Users/OCRONING/OneDrive - Environmental Protection Agency (EPA)/Profile/Documents/Chlorophyll_Temporal_Mismatch/Outputs/Figures/Wind/"

Table_filepath <- "C:/Users/OCRONING/OneDrive - Environmental Protection Agency (EPA)/Profile/Documents/Chlorophyll_Temporal_Mismatch/Outputs/Tables/Wind/"

Processed_filepath <- "C:/Users/OCRONING/OneDrive - Environmental Protection Agency (EPA)/Profile/Documents/Chlorophyll_Temporal_Mismatch/Processed_Data/Wind/"
```

#Function for filtering for data between 9am and 3pm
```{r}
filter_day <- function(data){
  Day <- data %>%
    mutate(noFieldTime = hour(data$DT) < 9 | hour(data$DT) >= 15)
  Day14 = Day[Day$noFieldTime == F, ] 
  
  hour15 <- dplyr::filter(data, grepl("15:00:00",DT))
  hour15$noFieldTime <- as.logical("FALSE")
  dayAll <- rbind(Day14, hour15)
  return(dayAll)
}
```

# Clean Wind Data
```{r}
#Read in Wind data 
HR_wind <- read.table(paste0(wd, "Wind/jlhaw_wind.txt"), header=TRUE, sep="\t");HR_wind <- HR_wind[,c(1:12)]
NH_wind <- read.table(paste0(wd, "Wind/jlnewhope_wind.txt"), header=TRUE, sep="\t")
WO_wind <- read.table(paste0(wd, "Wind/jlwhiteoak_wind.txt"), header=TRUE, sep="\t");WO_wind <- WO_wind[,c(1:12)]

#Combine into one df
windAll <- as.data.frame(rbind(HR_wind, NH_wind, WO_wind))
Wind <- windAll[,c(1:4,10,8:9)] 

#Extract sample time
Wind$sample_time <- substr(Wind$sample_time, 0, nchar(Wind$sample_time) - 6)
#Wind$gust_time <- substr(Wind$gust_time, 0, nchar(Wind$gust_time) - 6)

#Just focus on wind data (no gust)
Wind <- Wind[,c(1:4)]
names(Wind) <- c("Loc", "Datetime", "Wind_Speed", "Wind_dir")

#Convert character sample time to Datetime class
Wind$DT <- parse_date_time(as.character(Wind$Datetime), order = "%d/%m/%y %H:%M:%S", tz = 'EST') 

#Filter only samples that fall between 9am and 3pm
dayAll <- filter_day(Wind)
Wind_day = dayAll %>% select(-c(noFieldTime))

#Extract Date, month, year, and day from Datetime
Wind_day$Date <- substr(Wind_day$Datetime, 0, nchar(Wind_day$Datetime) - 9)
Wind_day <- na.omit(Wind_day)
Wind_day$month_name <- format(Wind_day$DT,"%B")
Wind_day$year <- as.numeric(format(Wind_day$DT,"%Y"))
Wind_day$day <- as.numeric(format(Wind_day$DT,"%d"))

#Export table
write.csv(Wind_day[c(1:4, 7:9),], paste0(Processed_filepath, "dailyWind10min.csv"), row.names = F)

rm(windAll, Wind, dayAll, HR_wind, NH_wind, WO_wind)
```

#Aggregate Wind by 30 min intervals
```{r}
#Split by location and recombine for ease of aggregation
NH_wind <- Wind_day[Wind_day$Loc == 'jlnewhope',]
HR_wind <- Wind_day[Wind_day$Loc == 'jlhaw',]
WO_wind <- Wind_day[Wind_day$Loc == 'jlwhiteoak',]

NH_wind$Loc <- 1
HR_wind$Loc <- 2
WO_wind$Loc <- 3

Wind_data <- as.data.frame(rbind(HR_wind, NH_wind, WO_wind))
Wind_data <- Wind_data[,c(1:5)]

#Aggregate by mean of 30 min intervals
Wind_data_30min <- Wind_data %>%
  group_by(Datetime=floor_date(DT, '30 min')) %>%
  summarize(avg_wind_speed=round(mean(Wind_Speed),2),
            avg_wind_dir=round(mean(Wind_dir),0),
            loc=mean(Loc))

#Redefine location
NH <- Wind_data_30min[Wind_data_30min$loc == 1,]; NH$loc <- "jlnewhope"
HR <- Wind_data_30min[Wind_data_30min$loc == 2,]; HR$loc <- "jlhaw"
WO <- Wind_data_30min[Wind_data_30min$loc == 3,]; WO$loc <- "jlwhiteoak"

Wind_data_30min <- as.data.frame(rbind(NH, HR, WO))

#Export table
write.csv(Wind_data_30min, file = paste0(Processed_filepath, "dailyWind30min.csv"), row.names = F)

rm(Wind_data, HR_wind, NH_wind, WO_wind, HR, NH, WO)
```

#Wind Speed and Direction Rose
```{r}
windRoseDF <- as.data.frame(cbind(Wind_day$Date, Wind_day$Wind_Speed, Wind_day$Wind_dir))

names(windRoseDF) <- c("date", "ws", "wd")
windRoseDF$Date2 <- as.Date(windRoseDF$date)
windRoseDF$date <- NULL
names(windRoseDF) <- c("ws", "wd", "date")

windRoseDF <- transform(windRoseDF, col1 = as.numeric(ws), col2 = as.numeric(wd))
windRoseDF$wd <- NULL
windRoseDF$ws <- NULL
names(windRoseDF) <- c("date", "ws", "wd")

png(paste0(Figure_filepath, "windRose.png") )
par(mar = c(5,5,5,5), xaxs="i", yaxs="i")
windRose(windRoseDF, angle = 30, width = 1, grid.line = 5, dig.lab = 2, paddle = F)
dev.off()

png(paste0(Figure_filepath, "windRoseSeasonal.png") )
par(mar = c(5,5,5,5), xaxs="i", yaxs="i")
windRose(windRoseDF, angle = 30, width = 1, grid.line = 5, dig.lab = 2, paddle = F, type = "season")
dev.off()

png(paste0(Figure_filepath, "windRoseMonthly.png") )
par(mar = c(5,5,5,5), xaxs="i", yaxs="i")
windRose(windRoseDF, angle = 30, width = 1, grid.line = 5, dig.lab = 2, paddle = F, type = "month")
dev.off()

rm(windRoseDF)
```

#Summary Wind Stats
```{r}
#Create function to extract wind speed stats
windStats <- function(windData){
  wsStats <- as.data.frame(round(rbind(mean(windData$Wind_Speed), median(windData$Wind_Speed), sd(windData$Wind_Speed), min(windData$Wind_Speed), max(windData$Wind_Speed)), 2))
  names(wsStats) <- c("Wind_Speed_Stats")
  
  wsQuantile <- as.data.frame(quantile(windData$Wind_Speed, probs = seq(0.25,0.75,0.25), na.rm = T, digits = 2, names = T ))
  names(wsQuantile) <- c("windSpeed")
  
  wdStats <- as.data.frame(round(rbind(mean(windData$Wind_dir), median(windData$Wind_dir), sd(windData$Wind_dir), min(windData$Wind_dir), max(windData$Wind_dir)), 2))
  names(wdStats) <- c("Wind_Dir_Stats")
  
  wdQuantile <- as.data.frame(quantile(windData$Wind_dir, probs = seq(0.25,0.75,0.25), na.rm = T, digits = 2, names = T ))
  names(wdQuantile) <- c("windDir")
  
  labels <- as.data.frame(c("mean", "median", "sd", "min", "max"))
  
  windStatsDF <- as.data.frame(cbind(labels,wsStats, wdStats))
  names(windStatsDF) <- c("Stats", "windSpeed", "windDir")
  
  quantile <- cbind(wsQuantile, wdQuantile)
  quantile$Stats <- row.names(quantile)
  quantile <- quantile[,c(3,1,2)]
  
  windStatsDF <- as.data.frame(rbind(windStatsDF, quantile))
  return(windStatsDF)
}

#Separate by location
HR_wind <- Wind_day[Wind_day$Loc == 'jlhaw', ]
NH_wind <- Wind_day[Wind_day$Loc == 'jlnewhope', ]
WO_wind <- Wind_day[Wind_day$Loc == 'jlwhiteoak', ]

#Apply stats function
allWindStats <- windStats(Wind_day)
HRWindStats <- windStats(HR_wind); names(HRWindStats) <- c("Stats", "HR_windSpeed", "HR_windDir")
NHWindStats <- windStats(NH_wind); names(NHWindStats) <- c("Stats", "NH_windSpeed", "NH_windDir")
WOWindStats <- windStats(WO_wind); names(WOWindStats) <- c("Stats", "WO_windSpeed", "WO_windDir")

#Create stats dateframe
statsList <- list(allWindStats, HRWindStats, NHWindStats, WOWindStats )
statsDF <- statsList %>% reduce(full_join, by='Stats')

#Export table
write.csv(statsDF, paste0(Table_filepath, "windSpeedStatsSummary.csv"), row.names = F)

rm(HR_wind, NH_wind, WO_wind, HRWindStats, NHWindStats, WOWindStats, statsList, statsDF)
```

#Wind Speed Histogram
```{r}
#Plot histogram, separated by location
ws_hist <- ggplot(Wind_day, aes(x = Wind_Speed, fill = factor(Loc))) +
  geom_histogram(color ="grey30", binwidth = 0.5, alpha=0.6, aes(fill = factor(Loc))) +
  labs(x = "Wind Speed [m/s]", y = "Frequency", fill = "Location") +
  ggtitle("UNC Buoy 10min Mean Wind Speed") +
  xlim(0,20) +
  geom_vline(aes(xintercept = allWindStats$windSpeed[1], col = "mean"), linetype = "solid", linewidth = 1, key_glyph = "smooth") +
  geom_vline(aes(xintercept = allWindStats$windSpeed[2], col = "median"), linetype = "solid", linewidth = 1, key_glyph = "smooth") +
  geom_vline(aes(xintercept = (allWindStats$windSpeed[1] + allWindStats$windSpeed[3]), col = "upper_sd"), linetype = "solid", linewidth = 1, 
             key_glyph = "smooth") + geom_vline(aes(xintercept = (allWindStats$windSpeed[1] - allWindStats$windSpeed[3]), col = "lower_sd"), linetype = "solid", linewidth = 1,  key_glyph = "smooth") +
  geom_vline(aes(xintercept = allWindStats$windSpeed[4], col = "min"), linetype = "solid", linewidth = 1, key_glyph = "smooth") +
  geom_vline(aes(xintercept = allWindStats$windSpeed[5], col = "max"), linetype = "solid", linewidth = 1, key_glyph = "smooth") +
  scale_color_manual(name = "Statistics", values = c(mean = "red", median = "blue", upper_sd = "purple", lower_sd = "orange", min = "#090010", max = "forestgreen")) +
  scale_color_manual(breaks = c("jlhaw",  "jlnewhope", "jlwhiteoak"),
                           values= c("#E41A1C", "#377EB8", "#4DAF4A")) +
  theme(plot.title = element_text(hjust = 0.5))

ws_hist

ggsave(path = Figure_filepath, filename = "windSpeedHist.png", device = "png", plot = ws_hist, width = 7, height = 5.5, dpi = 300, units = "in")
rm(ws_hist, allWindStats)
```

#Daily Wind Stats
```{r}
#Stats by Buoy
Daily_speed_max <- aggregate(Wind_day$Wind_Speed, by = list(Wind_day$Date, Wind_day$Loc), max)
Daily_speed_min <- aggregate(Wind_day$Wind_Speed, by = list(Wind_day$Date, Wind_day$Loc), min)
Daily_speed_mean <- aggregate(Wind_day$Wind_Speed, by = list(Wind_day$Date, Wind_day$Loc), mean)
Daily_speed_count <- Wind_day %>% count(Date, Loc)

Range_buoy <- as.data.frame(cbind(Daily_speed_max, Daily_speed_min$x, Daily_speed_mean$x, Daily_speed_count$n))
names(Range_buoy) <- c('Date',"Loc", 'Daily_max_wind', 'Daily_min_wind', 'Daily_mean_wind', "Daily_n_obs_wind")
Range_buoy$Daily_range_wind <- Range_buoy$Daily_max_wind - Range_buoy$Daily_min_wind

Range_buoy$Date <- as.Date(Range_buoy$Date, format = "%d/%m/%Y")

#Export table
write.csv(Range_buoy, file = paste0(Table_filepath, "windSpeedStatsDaily.csv"), row.names = F)

rm(Daily_speed_max, Daily_speed_mean, Daily_speed_min)

```

#Plot Daily Wind Time Series by Buoy
```{r}
#Extract month, year, and day from date of daily stats
Range_buoy$month_name <- format(Range_buoy$Date,"%B")
Range_buoy$year <- as.numeric(format(Range_buoy$Date,"%Y"))
Range_buoy$day <- as.numeric(format(Range_buoy$Date,"%d"))

#Group months by season
JJA <- c("June", "July", "August")
SON <- c("September", "October", "November")
DJF <- c("December", "January", "February")
MMA <- c("March", "April", "May")

#Make dummies
makeBlank <- function(year){
  Blank <- data.frame(matrix(ncol = ncol(Range_buoy), nrow = 12))
  names(Blank) <- names(Range_buoy)
  Blank$month_name <- c(unlist(list(JJA, SON, DJF, MMA)))
  Blank$year <- year
  return(Blank)
}

Available_years <- unique(Range_buoy$year)
Blank_years <- lapply(Available_years,makeBlank)
Blank_df <- do.call(rbind, Blank_years)

Range_buoy <- as.data.frame(rbind(Range_buoy, Blank_df))

#Split by season
Seasons <- c("Summer", "Fall", "Winter", "Spring")
Summer <- Range_buoy[Range_buoy$month_name %in% JJA,]
Fall <- Range_buoy[Range_buoy$month_name %in% SON,]
Winter <- Range_buoy[Range_buoy$month_name %in% DJF,]
Spring <- Range_buoy[Range_buoy$month_name %in% MMA,]
seasonAll <- list(Summer, Fall, Winter, Spring)

#Plot time series
for (s in 1:length(Seasons)){
  Season <- Seasons[s]
  SeasonDF <- as.data.frame(seasonAll[s])
  Available_years <- unique(SeasonDF$year)

  for (i in 1:length(Available_years)){
    Range_year <- SeasonDF[as.numeric(SeasonDF$year) == Available_years[i],]
    ind <- (colSums(is.na(Range_year)) == nrow(Range_year))
    
    if (ind[[1]] == FALSE){
      ts_buoy_year <- ggplot(data=na.omit(Range_year), aes(day, Daily_mean_wind, group = interaction(factor(month_name), factor(Loc)))) + 
        geom_line(aes(colour = factor(Loc))) + 
        geom_point(aes(colour = factor(Loc)), size = 1) +
        geom_errorbar(aes(ymin=Daily_min_wind, ymax=Daily_max_wind, color = factor(Loc)), width=.5) +
        facet_wrap(~month_name, ncol=1, strip.position = "right", drop = F) +
        labs(y= "Wind Speed [m/s]", x = "Day of Month", color = "Buoy Location") +
        theme(axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5), 
              panel.grid.minor = element_blank(),
              plot.title = element_text(hjust = 0.5)) + 
        scale_color_manual(breaks = c("jlhaw",  "jlnewhope", "jlwhiteoak"),
                           values= c("#E41A1C", "#377EB8", "#4DAF4A")) +
        ggtitle(paste0("Wind Speed ", Seasons[s], " ", Available_years[i]," Time-Series"))
      
      ggsave(filename=paste0(Seasons[s], "_", Available_years[i],"_buoyWindTimeSeries.png"), plot = ts_buoy_year, device = "png", path = paste0(Figure_filepath, "Daily_TimeSeries/", Season, "/"), width = 6, height = 5, dpi = 300, units = "in")
    }
  }
}

```
